### ISSUE TITLE
关于数据集路径的问题

### ISSUE THREAD

**Issue by Chenguang-Wang** [honglianghe/CDNet#1]
你好，我昨天下载了那两个数据集。
请问我该如何在项目路径中放置这两个数据集？我尝试按readme中的来但有问题。
预处理需要提前做吗？还是直接将原始数据按路径放置代码就能跑起来了？
感谢！

**Comment by honglianghe** [comment]
嗯，这两个数据集是需要先切patch的，我把处理后的数据整理好放到百度网盘，下载后解压放到CDNet/data目录下。
下载地址如下：
CPM：链接：https://pan.baidu.com/s/1ijIradUshA-VvN8xuSw6Uw  提取码：f62t
MoNuSeg 链接：https://pan.baidu.com/s/1fTgNx8t-26YteuNMMp8t9w  提取码：adzc
注：MoNuSeg数据官网给数据集的时候曾经放过很多不同的版本，我曾经被这个坑过。目前用的是最原始的版本，和HoVer-Net的是一样的。

**Comment by honglianghe** [comment]
@wangchen0520  嗯，这两个数据集是需要先切patch的，我把处理后的数据整理好放到百度网盘，下载后解压放到CDNet/data目录下。
下载地址如下：
CPM：链接：https://pan.baidu.com/s/1ijIradUshA-VvN8xuSw6Uw 提取码：f62t
MoNuSeg 链接：https://pan.baidu.com/s/1fTgNx8t-26YteuNMMp8t9w 提取码：adzc
注：MoNuSeg数据官网给数据集的时候曾经放过很多不同的版本，我曾经被这个坑过。目前用的是最原始的版本，和HoVer-Net的是一样的。

**Comment by Chenguang-Wang** [comment]
已经下载到了，非常感谢！
我就说自己从官网下载到的MoNuSeg数据集是37+14。

**Comment by Chenguang-Wang** [comment]
你好，能否在代码中补充一个python和各个包的版本文件？

**Comment by wangchen0520** [comment]
@honglianghe

**Comment by honglianghe** [comment]
> 你好，能否在代码中补充一个python和各个包的版本文件？

@Chenguang-Wang 你好，抱歉回复晚了。最近我们那台服务器拿去修了，我之后上传一个各个包的完整版本文件。 不过基本上你跑的时候报什么错安装什么包就可以。如果你哪个包报版本有问题，可以和我说。

**Comment by xiaona123456** [comment]
> 
您好 ，可以发一下数据集的百度网盘链接吗，那个超过访问人数 不能下载了

**Comment by lzc-David** [comment]
> 你好，我昨天下载了那两个数据集。 请问我该如何在项目路径中放置这两个数据集？我尝试按readme中的来但有问题。 预处理需要提前做吗？还是直接将原始数据按路径放置代码就能跑起来了？ 感谢！

你好    作者的数据集超过访问人数不能下载了       请问你可以分享一下嘛

**Comment by honglianghe** [comment]
@lzc-David 
您好，我在Issue #5 里重新提供了新的分享，链接如下：
CPM：链接：https://pan.baidu.com/s/16cAzzUBo7Z36Q6s7KSR65Q 提取码：0ytt
MoNuSeg 链接：https://pan.baidu.com/s/1gGLIQyUKnalsuJzl-U5OBw 提取码：m0z5
