### ISSUE TITLE
CDNet actual model source code

### ISSUE THREAD

**Issue by erik-koynov** [honglianghe/CDNet#2]
Hi guys, you have implemented many models, but which one of them is/are actually the CDNet? As default training model you have specified a model, whose name is not CDNet so I got a bit confused :)

**Comment by honglianghe** [comment]
Hi, the code of CDNet (UNet as backbone) is model_unet_rev1.py (in CDNet/models/dam/).

**Comment by honglianghe** [comment]
Hi, @erik-koynov ! The code of CDNet (UNet as backbone) is model_unet_rev1.py (in CDNet/models/dam/).

**Comment by erik-koynov** [comment]
Thank you very much!

**Comment by Lewislou** [comment]
> Hi, @erik-koynov ! The code of CDNet (UNet as backbone) is model_unet_rev1.py (in CDNet/models/dam/).

There are different backbones in model_unet_rev1.py, your original code is referring to Vgg16_bn. Is theVgg16_bn the backbone you used in CDNet?

**Comment by honglianghe** [comment]
@Lewislou Hello, U-Net is my backbone, VGG16-bn is just an encoding module. It doesn't matter that you can use a different backbone in your model.

**Comment by Lewislou** [comment]
> @Lewislou Hello, U-Net is my backbone, VGG16-bn is just an encoding module. It doesn't matter that you can use a different backbone in your model.

Yeah, I mean, they are not the same, the choice of the different components in your U-net backbone may change the performance. I did not find details in your paper. In your code, there are different choices, which one that you choose for your paper? The unet_encoder or resnet or others?
![image](https://user-images.githubusercontent.com/23080469/164365154-e32832c0-2c8f-4761-aaca-3a4b65361ee3.png)

**Comment by honglianghe** [comment]
@Lewislou The results in our paper all use vgg16_bn. Since our model can be adapted to various backbones and use different components, we provide readers with various options in the code.
