### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by kechunl** [honglianghe/CDNet#3]
Hello, I'm trying to run your excellent CDNet on a customized dataset. It looks like I need to specify 'data_dir' and 'weight_map_dir' in options.py. Could you explain how you organize the data, especially what is in the two directories? And could you point me to the code you preprocess the data? Thank you!

**Comment by honglianghe** [comment]
Hello @kechunl , you can obtain the datasets (we used) from  (CPM) https://pan.baidu.com/s/1ijIradUshA-VvN8xuSw6Uw (password: f62t) and  (MoNuSeg) https://pan.baidu.com/s/1fTgNx8t-26YteuNMMp8t9w (password: adzc). 
We didn't use 'weight_map_dir', you can ignore it.

**Comment by eshasadia** [comment]
![image](https://user-images.githubusercontent.com/45667822/173318047-2a6bbb29-0207-4ecd-ae23-47db31fbd791.png)
Hi, Can you please reshare datasets linked as data isn't available on the above links
