### ISSUE TITLE
Data links not working

### ISSUE THREAD

**Issue by eshasadia** [honglianghe/CDNet#6]
Hi, Can you please reshare  datasets links as data isn't available on the links shared earlier.
![image](https://user-images.githubusercontent.com/45667822/173318319-2ec2c9a8-001e-49c9-a97d-aedea04bc0b9.png)

**Comment by honglianghe** [comment]
dataset link:
(CPM17) https://pan.baidu.com/s/16cAzzUBo7Z36Q6s7KSR65Q (password: 0ytt)
(MoNuSeg) https://pan.baidu.com/s/1gGLIQyUKnalsuJzl-U5OBw (password: m0z5)

**Comment by zmxsdu** [comment]
Data links not working , I wanna find the links of Kumar ,can you please reshare the datasets of Kumar.
