### ISSUE TITLE
数据集加载问题

### ISSUE THREAD

**Issue by Ericgupeng** [honglianghe/CDNet#8]
您好，复现您的代码时，使用的是(MoNuSeg, CPM17) 两个dataset，但是一直报错，
Traceback (most recent call last):
  File "/media/kemove/ericgu/CDNet-main/train.py", line 528, in <module>
    main()
  File "/media/kemove/ericgu/CDNet-main/train.py", line 293, in main
    dsets[x] = DataFolder(dir_list, post_fix, num_channels, data_transforms[x])
  File "/media/kemove/ericgu/CDNet-main/data_folder.py", line 94, in __init__
    raise(RuntimeError('Found 0 image pairs in given directories.'))
RuntimeError: Found 0 image pairs in given directories.
为什么要设置三个train_300文件夹，还需要对(MoNuSeg, CPM17)再进行什么处理吗？
我看您的文章还对图像进行了一些label
希望您能详细指点，谢谢！

**Comment by Mierer** [comment]
Hello, how to obtain the weight map ?
post_fix=['weight.png','label.png']
RuntimeError: Found 0 image pairs in given directories.

**Comment by MukulKadaskar** [comment]
> Hello, how to obtain the weight map ? post_fix=['weight.png','label.png'] RuntimeError: Found 0 image pairs in given directories.

Any update on this issue.

**Comment by honglianghe** [comment]
@Mierer The weight map is not necessary in the code, you can remove it.

**Comment by honglianghe** [comment]
@ericgupeng 你好，感谢关注。不好意思回复晚了。设置300的意思是我在最开始的时候会对图像取patch（大小为300*300，因为原先1000*1000的图的数量太少了，需要通过这个来增大图片数量。设置多大尺寸其实可以根据自己的喜好来的）。
